baseURL: "https://monbossadit.fr/"
title: "{ MonBossADit... }"
copyright: "© { MonBossADit... }"
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

defaultContentLanguage: fr

pagination:
  pagerSize: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Les anecdotes de managers déconnectés de la réalité"
  author: "{ MonBossADit... }"

  defaultTheme: auto
  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowShareButtons: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: false

  homeInfoParams:
    Title: "Mon Boss A Dit..."
    Content: |
      😱 Parce que certaines phrases ne devraient jamais être prononcées en réunion.<br>
      **Vraies.**<br>
      **Vécues.**<br>
      **Impossibles à inventer.**<br>
      Soumets la tienne.

  # socialIcons:
  #   - name: github
  #     title: View Source on Github
  #     url: "https://github.com/adityatelange/hugo-PaperMod"
  #   - name: Discord
  #     title: Join discord community
  #     url: "https://discord.gg/ahpmTvhVmp"
  #   - name: X
  #     title: Share PaperMod on X/Twitter
  #     url: "https://x.com/intent/tweet/?text=Checkout%20Hugo%20PaperMod%20%E2%9C%A8%0AA%20fast,%20clean,%20responsive%20Hugo%20theme.&url=https://github.com/adityatelange/hugo-PaperMod&hashtags=Hugo,PaperMod"
  #   - name: KoFi
  #     title: Buy me a Ko-Fi :)
  #     url: "https://ko-fi.com/adityatelange"

menu:
  main:
    # - name: Anecdotes
    #   url: /posts/
    #   weight: 1
    - name: Soumettre
      url: /submit/
      weight: 2
    - name: Archives
      url: /archives/
      weight: 3
    - name: CGU
      url: /cgu/
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false